markdown: rdiscount
permalink: /:year/:month/:title/
url: http://kuangzhou.github.io/en
title : Be constancy to purpose
tagline: Cease to struggle and you cease to live 
author: 周旷(KuangZHOU) 
pygments: true

